# Generated by Django 4.2 on 2023-04-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20, null=True)),
                ('abv', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'states'},
        ),
    ]
