# Generated by Django 4.2 on 2023-04-17 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('states', '0002_activity_alter_state_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='favorite',
            field=models.ManyToManyField(related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
