# Generated by Django 4.2 on 2023-04-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_activity_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
