# Generated by Django 4.2 on 2023-04-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0004_activity_description_activity_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
